Repository deploifai/cli, pull requests merged in 2022-07, with the labels that each got.

#19 Project Browse Command
  deploifai/api/__init__.py
  deploifai/context.py
  deploifai/project/__init__.py
  deploifai/project/browse.py
  deploifai/utilities/environment.py
  deploifai/utilities/frontend_routing.py
  setup.py
Labels: summer 22

#23 mlflow integration command
  deploifai/cli.py
  deploifai/mlflow/__init__.py
  deploifai/mlflow/get_setup.py
  requirements.txt
  setup.py
Labels: summer 22

#24 Dataset create
  deploifai/api/__init__.py
  deploifai/context.py
  deploifai/data/__init__.py
  deploifai/data/create.py
  deploifai/data/init.py
Labels: summer 22

#38 Dataset init
  .gitignore
  deploifai/api/__init__.py
  deploifai/context.py
  deploifai/dataset/create.py
  deploifai/dataset/init.py
  deploifai/dataset/push.py
  deploifai/project/create.py
  deploifai/utilities/config/__init__.py
  deploifai/utilities/config/dataset_config.py
  deploifai/utilities/config/find_config_filepath.py
  deploifai/utilities/config/local_config.py
Labels: enhancement, summer 22

#39 Documentation
  .gitignore
  deploifai/mlflow/__init__.py
  docs/application.md
  docs/auth.md
  docs/cloud-profile.md
  docs/dataset.md
  docs/index.md
  docs/mlflow.md
  docs/project.md
  docs/server.md
  docs/workspace.md
  mkdocs.yml
  readme.md
Labels: documentation, summer 22

#40 add setuptools scm to release package based on git tags
  .github/workflows/dev.yml
  .github/workflows/release.yml
  pyproject.toml
  setup.py
Labels: enhancement

#45 fix cli version option
  deploifai/cli.py
Labels: bug

#46 project init command added
  deploifai/project/__init__.py
  deploifai/project/create.py
  deploifai/project/init.py
  deploifai/utilities/config/local_config.py
Labels: enhancement, summer 22
