Repository deploifai/cli, pull requests merged in 2022-08, with the labels that each got.

#50 Server State and Project Info
  .gitignore
  deploifai/api/__init__.py
  deploifai/project/__init__.py
  deploifai/project/info.py
  deploifai/server/__init__.py
  deploifai/server/list.py
  deploifai/server/start.py
  deploifai/server/stop.py
  deploifai/utilities/server_state.py
Labels: enhancement, summer 22

#54 added new directory creation for dataset create
  deploifai/dataset/create.py
  deploifai/utilities/config/dataset_config.py
Labels: bug

#56 fix resource access token query for mlflow get-setup command
  deploifai/mlflow/get_setup.py
Labels: bug

#55 Fix dataset list and info
  deploifai/api/__init__.py
  deploifai/dataset/info.py
  deploifai/dataset/list.py
  deploifai/utilities/frontend_routing.py
Labels: bug, enhancement, summer 22
